---
  server_url: # -- replace with arn:aws:ssm:<region>:<account_id>:parameter/${Name}_domain_name --
  listen_addr: 0.0.0.0:443
  metrics_listen_addr: 127.0.0.1:9090
  grpc_listen_addr: 0.0.0.0:8443
  grpc_allow_insecure: false
  private_key_path: /var/lib/headscale/private.key
  noise:
    private_key_path: /var/lib/headscale/noise_private.key
  ip_prefixes:
    - fd7a:115c:a1e0::/48
    - 100.64.0.0/10
  derp:
    server:
      enabled: false
    urls:
      - https://controlplane.tailscale.com/derpmap/default
    paths: []
    auto_update_enabled: true
    update_frequency: 24h
  disable_check_updates: false
  ephemeral_node_inactivity_timeout: 30m
  node_update_check_interval: 10s
  db_type: sqlite3
  db_path: /var/lib/headscale/db.sqlite
  acme_url: https://acme-v02.api.letsencrypt.org/directory
  acme_email: # -- replace with "arn:aws:ssm:<region>:<account_id>:parameter/${Name}_acme_email" --
  tls_letsencrypt_hostname: # -- replace with arn:aws:ssm:<region>:<account_id>:parameter/${Name}_domain_name --
  tls_letsencrypt_cache_dir: /var/lib/headscale/cache
  tls_letsencrypt_challenge_type: TLS-ALPN-01
  tls_letsencrypt_listen: ":http"
  log:
    format: text
    level: info
  acl_policy_path: /etc/headscale/acl.json
  unix_socket: /var/run/headscale/headscale.sock
  unix_socket_permission: "0770"
  logtail:
    enabled: false
  randomize_client_port: true
