#cloud-config
repo_update: true
repo_upgrade: all

packages:
 - cron
 - curl
 - inotify-hookable
 - inotify-tools
 - jq
 - sed
 - sqlite3
 - sudo
 - vim

runcmd:
 - [ 'aws', 's3', 'cp', 's3://<my-bucket>/setup.sh', '/tmp/setup.sh' ]
 - [ chmod, +x, '/tmp/setup.sh' ]
 - /tmp/setup.sh
